import { CatalogItem } from './types';

const RAW_ITEMS: Array<Record<string, any>> = [
  {
    id: 'for_bar_01',
    reference: 'FOR-BAR-180',
    designation: 'Barre conique H22 Longueur 1.8m',
    unit: 'PIECE',
    price: 2800,
    functionalCategory: 'Barres de Forage',
    component: 'Barre conique',
    subComponent: 'Acier allié chrome-molybdène',
    compatibility: 'Tous perforateurs 22x108',
    suggestedType: 'CONSOMMABLES',
    stockQty: 45,
    minStock: 20,
    criticalStock: 10,
    leadTimeDays: 14,
    commonName: 'Barre 1m80',
    searchTags: ['barre', 'forage', 'conique', 'h22', '1.8m'],
    notes: 'Queue 22x108mm, acier allié traité',
  },
  {
    id: 'for_bar_02',
    reference: 'FOR-BAR-280',
    designation: 'Barre conique H22 Longueur 2.8m',
    unit: 'PIECE',
    price: 4200,
    functionalCategory: 'Barres de Forage',
    component: 'Barre conique',
    subComponent: 'Acier allié chrome-molybdène',
    compatibility: 'Tous perforateurs 22x108',
    suggestedType: 'CONSOMMABLES',
    stockQty: 30,
    minStock: 15,
    criticalStock: 8,
    leadTimeDays: 14,
    commonName: 'Barre 2m80',
    searchTags: ['barre', 'forage', 'conique', 'h22', '2.8m'],
    notes: 'Queue 22x108mm, acier allié traité',
  },
  {
    id: 'for_tai_01',
    reference: 'FOR-TAI-038',
    designation: 'Taillant conique 38mm',
    unit: 'PIECE',
    price: 850,
    functionalCategory: 'Taillants & Boutons',
    component: 'Taillant conique',
    subComponent: 'Carbure de tungstène',
    compatibility: 'Tous perforateurs 22x108',
    suggestedType: 'CONSOMMABLES',
    stockQty: 120,
    minStock: 50,
    criticalStock: 20,
    leadTimeDays: 7,
    commonName: 'Taillant 38mm',
    searchTags: ['taillant', 'conique', '38mm', 'carbure'],
    notes: 'Diamètre 38mm, angle 110°',
  },
  {
    id: 'for_tai_02',
    reference: 'FOR-TAI-041',
    designation: 'Taillant conique 41mm',
    unit: 'PIECE',
    price: 950,
    functionalCategory: 'Taillants & Boutons',
    component: 'Taillant conique',
    subComponent: 'Carbure de tungstène',
    compatibility: 'Tous perforateurs 22x108',
    suggestedType: 'CONSOMMABLES',
    stockQty: 80,
    minStock: 40,
    criticalStock: 15,
    leadTimeDays: 7,
    commonName: 'Taillant 41mm',
    searchTags: ['taillant', 'conique', '41mm', 'carbure'],
    notes: 'Diamètre 41mm, angle 110°',
  },
  {
    id: 'for_tai_03',
    reference: 'FOR-TAI-045',
    designation: 'Taillant bouton 45mm',
    unit: 'PIECE',
    price: 1200,
    functionalCategory: 'Taillants & Boutons',
    component: 'Taillant bouton',
    subComponent: 'Carbure de tungstène',
    compatibility: 'Tous perforateurs 22x108',
    suggestedType: 'CONSOMMABLES',
    stockQty: 60,
    minStock: 30,
    criticalStock: 12,
    leadTimeDays: 10,
    commonName: 'Bouton 45mm',
    searchTags: ['taillant', 'bouton', '45mm', 'carbure'],
    notes: 'Diamètre 45mm, 7 boutons',
  },
  {
    id: 'for_mec_01',
    reference: 'FOR-MEC-120',
    designation: 'Mèche de forage H22 Longueur 1.2m',
    unit: 'PIECE',
    price: 3200,
    functionalCategory: 'Mèches & Tiges',
    component: 'Mèche de forage',
    subComponent: 'Acier allié traité',
    compatibility: 'Tous perforateurs 22x108',
    suggestedType: 'CONSOMMABLES',
    stockQty: 25,
    minStock: 12,
    criticalStock: 5,
    leadTimeDays: 21,
    commonName: 'Mèche 1m20',
    searchTags: ['mèche', 'forage', 'h22', '1.2m'],
    notes: 'Queue 22x108mm, tête cross X',
  },
  {
    id: 'for_ada_01',
    reference: 'FOR-ADA-2245',
    designation: 'Adaptateur queue 22x108 / T45',
    unit: 'PIECE',
    price: 4500,
    functionalCategory: 'Adaptateurs & Raccords',
    component: 'Adaptateur',
    subComponent: 'Acier allié traité',
    compatibility: 'Tous perforateurs 22x108',
    suggestedType: 'CONSOMMABLES',
    stockQty: 15,
    minStock: 8,
    criticalStock: 3,
    leadTimeDays: 30,
    commonName: 'Adaptateur 22/T45',
    searchTags: ['adaptateur', '22x108', 't45', 'raccord'],
    notes: 'Connexion 22x108 vers T45',
  },
  {
    id: 'for_ron_01',
    reference: 'FOR-RON-045',
    designation: 'Rondelle de fond de trou',
    unit: 'PIECE',
    price: 350,
    functionalCategory: 'Accessoires de Forage',
    component: 'Rondelle fond de trou',
    subComponent: 'Acier trempé',
    compatibility: 'Tous perforateurs',
    suggestedType: 'CONSOMMABLES',
    stockQty: 200,
    minStock: 100,
    criticalStock: 40,
    leadTimeDays: 7,
    commonName: 'Rondelle fond',
    searchTags: ['rondelle', 'fond de trou', 'acier'],
    notes: 'Ø45mm, épaisseur 5mm',
  },
  {
    id: 'for_tub_01',
    reference: 'FOR-TUB-045',
    designation: 'Tube guide de forage Ø45mm',
    unit: 'PIECE',
    price: 1800,
    functionalCategory: 'Accessoires de Forage',
    component: 'Tube guide',
    subComponent: 'Acier allié',
    compatibility: 'Tous perforateurs',
    suggestedType: 'CONSOMMABLES',
    stockQty: 40,
    minStock: 20,
    criticalStock: 8,
    leadTimeDays: 14,
    commonName: 'Tube guide 45',
    searchTags: ['tube', 'guide', 'forage', '45mm'],
    notes: 'Ø45mm, longueur 1m',
  },
];

export const CONSOMMABLES_FORAGE_CATALOG: CatalogItem[] = RAW_ITEMS.map(it => ({
  id: it.id,
  reference: it.reference,
  designation: it.designation,
  unit: it.unit,
  price: it.price,
  functionalCategory: it.functionalCategory,
  component: it.component,
  subComponent: it.subComponent,
  compatibility: it.compatibility,
  suggestedType: it.suggestedType,
  stockQty: it.stockQty ?? Math.round(Math.sin(it.price) * 15 + 20),
  minStock: it.minStock ?? 10,
  criticalStock: it.criticalStock ?? 5,
  leadTimeDays: it.leadTimeDays ?? 14,
  commonName: it.commonName,
  searchTags: it.searchTags,
  notes: it.notes,
})) as CatalogItem[];
