import { CatalogItem } from './types';

export const CATALOG_VERSION = '1.3'; // Increment this to force refresh

export const MASTER_CATALOG: CatalogItem[] = [
  // --- SYSTEME DE PROPULSION ET MOTEUR ---
  { id: 'st2g_01', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Bloc moteur', subComponent: '', reference: '5580 0088 00 / 5575 4856 00', designation: 'Bloc moteur complet', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_02', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Vilebrequin', subComponent: '', reference: '5580 0088 05', designation: 'Vilebrequin', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_03', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Vilebrequin', subComponent: 'Coussinet principal', reference: '3128 0459 00', designation: 'Coussinet principal', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_04', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Vilebrequin', subComponent: 'Coussinet de bielle', reference: '3128 0460 00', designation: 'Coussinet de bielle', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_05', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Vilebrequin', subComponent: 'Joint spy avant', reference: '5515 5001 00 b', designation: 'Joint spy avant', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_06', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Vilebrequin', subComponent: 'Joint spy arriere', reference: '5515 5002 00 b', designation: 'Joint spy arriere', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_07', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Vilebrequin', subComponent: 'bague de butée', reference: '3128 3004 00 a', designation: 'Bague de butée', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_08', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Moteur Complet', component: 'Bielles', subComponent: '', reference: '5580 0088 06 (kit)', designation: 'Bielles (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  
  { id: 'st2g_09', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Pistons', subComponent: '', reference: '5580 0088 01 (kit)', designation: 'Pistons (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_10', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Pistons', subComponent: 'Couronne de piston', reference: '3128 3005 00 a', designation: 'Couronne de piston', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_11', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Pistons', subComponent: 'juppe de piston', reference: '5516 0019 00 a', designation: 'Juppe de piston', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_12', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Pistons', subComponent: 'axe de piston', reference: '3128 3028 00 a', designation: 'Axe de piston', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_13', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Pistons', subComponent: 'circlips axe piston', reference: '5515 5013 00 a', designation: 'Circlips axe piston', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_14', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Pistons', subComponent: 'jet de refroidissement piston', reference: '3128 3029 00 a', designation: 'Jet de refroidissement piston', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_15', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Pistons', subComponent: 'Bague de piston', reference: '5516 0020 00 a', designation: 'Bague de piston', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_16', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Segments', subComponent: '', reference: '5580 0088 07 (kit)', designation: 'Segments (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_17', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Segments', subComponent: 'Segment de compression supérieur', reference: '5516 0020 00 a', designation: 'Segment de compression supérieur', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_18', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Segments', subComponent: 'segment de compression intermédiaire', reference: '5516 0002 00 a', designation: 'Segment de compression intermédiaire', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_19', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Segments', subComponent: "segment d'huile", reference: '5516 0021 00 a', designation: "Segment d'huile", suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_20', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Segments', subComponent: "expandeur d'huile", reference: '3128 3030 00 a', designation: "Expandeur d'huile", suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_21', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pistons et Segments', component: 'Segments', subComponent: 'segment rateau', reference: '3128 3031 00 a', designation: 'Segment rateau', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_22', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Culasse', component: 'Culasse', subComponent: '', reference: '5580 0088 02', designation: 'Culasse', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_23', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Culasse', component: 'Soupapes', subComponent: '', reference: '5580 0088 08 (kit)', designation: 'Soupapes (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_24', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Culasse', component: 'Guides de soupapes', subComponent: '', reference: '5580 0088 09 (kit)', designation: 'Guides de soupapes (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_25', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Culasse', component: 'Joint de culasse', subComponent: '', reference: '5580 0088 10', designation: 'Joint de culasse', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_26', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Culasse', component: 'Vis de culasse', subComponent: '', reference: '5580 0088 11 (kit)', designation: 'Vis de culasse (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_27', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Turbo', component: 'Turbine', subComponent: '', reference: '5580 0088 03 a', designation: 'Turbine', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_28', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Turbo', component: 'Compresseur', subComponent: '', reference: '5580 0088 03 b', designation: 'Compresseur', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_29', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Turbo', component: 'Joints et roulements', subComponent: '', reference: '5580 0088 03 c (kit)', designation: 'Joints et roulements (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_30', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Injecteurs', component: 'Injecteur unitaire', subComponent: '', reference: '5580 0088 04 a (set de 4)', designation: 'Injecteur unitaire (set de 4)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_31', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Injecteurs', component: 'Joints d\'injecteurs', subComponent: '', reference: '5580 0088 04 b (kit)', designation: 'Joints d\'injecteurs (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_32', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Injecteurs', component: 'Buses', subComponent: '', reference: '5580 0088 04 c (kit)', designation: 'Buses (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_33', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Radiateur', component: 'Ailettes', subComponent: '', reference: '5515 5000 00 a', designation: 'Ailettes', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_34', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Radiateur', component: 'Bouchon pression', subComponent: '', reference: '5515 5000 00 b', designation: 'Bouchon pression', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_35', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Radiateur', component: 'Durites', subComponent: '', reference: '5515 5000 00 c (kit)', designation: 'Durites (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_36', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Ventilateur Hydraulique', component: 'Lames', subComponent: '', reference: '3128 2000 00 a', designation: 'Lames', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_37', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Ventilateur Hydraulique', component: 'Moteur hydraulique', subComponent: '', reference: '3128 2000 00 b', designation: 'Moteur hydraulique', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_38', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Ventilateur Hydraulique', component: 'Roulements', subComponent: '', reference: '3128 2000 00 c (kit)', designation: 'Roulements (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_39', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Thermostat', component: 'Corps', subComponent: '', reference: '2657 8000 00 a', designation: 'Corps', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_40', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Thermostat', component: 'Joint', subComponent: '', reference: '2657 8000 00 b', designation: 'Joint', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_41', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Courroies et bougies', component: 'Courroie distribution', subComponent: 'Courroie complete', reference: '3128 3032 00 a', designation: 'Courroie complète', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_42', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Courroies et bougies', component: 'Courroie distribution', subComponent: 'Tendeur courroie', reference: '5516 0022 00 a', designation: 'Tendeur courroie', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_43', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Courroies et bougies', component: 'Courroie distribution', subComponent: 'poulie tendeur', reference: '5516 0023 00 a', designation: 'poulie tendeur', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_44', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Courroies et bougies', component: 'Courroie accessoire', subComponent: 'Courroie multi V', reference: '3128 3033 00 a', designation: 'Courroie multi V', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_45', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Courroies et bougies', component: 'Courroie accessoire', subComponent: 'Tendeur accessoire', reference: '5516 0024 00 a', designation: 'Tendeur accessoire', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_46', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Courroies et bougies', component: 'Bougies allumage', subComponent: 'Bougie préchauffage', reference: '3128 3034 00 a', designation: 'Bougie préchauffage', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_47', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Courroies et bougies', component: 'Bougies allumage', subComponent: 'Relais bougies', reference: '5516 0025 00 a', designation: 'Relais bougies', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_48', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pompe à injection', component: 'Pompe complete', subComponent: '', reference: '3128 3035 00 a', designation: 'Pompe complète', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_49', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pompe à injection', component: 'Injecteur', subComponent: '', reference: '5516 0026 00 a', designation: 'Injecteur', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_50', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pompe à injection', component: 'Joint injecteur', subComponent: '', reference: '5515 5014 00 b', designation: 'Joint injecteur', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_51', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pompe à injection', component: 'Rail commun', subComponent: '', reference: '3128 3036 00 b', designation: 'Rail commun', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_52', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pompe Haute Pression', component: 'Rotor', subComponent: '', reference: '5580 0083 35 a', designation: 'Rotor', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_53', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Pompe Haute Pression', component: 'Joints', subComponent: '', reference: '5580 0083 35 b (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_54', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Filtres', component: 'Filtre à huile', subComponent: 'filtre huile complet', reference: '5515 5015 00 b', designation: 'filtre huile complet', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_55', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Filtres', component: 'Filtre à huile', subComponent: 'joint filtre huile', reference: '3128 3037 00 a', designation: 'joint filtre huile', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_56', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Filtres', component: 'filtre à air', subComponent: 'filtre air principal', reference: '5516 0027 00 a', designation: 'filtre air principal', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_57', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Filtres', component: 'filtre à air', subComponent: 'filtre air sécurité', reference: '5516 0028 00 a', designation: 'filtre air sécurité', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_58', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Filtres', component: 'Filtre carburant', subComponent: 'filtre carburant complet', reference: '5516 0029 00 a', designation: 'filtre carburant complet', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_59', functionalCategory: 'Système de Propulsion et Moteur', subCategory: 'Filtres', component: 'Filtre carburant', subComponent: 'séparateur eau', reference: '3128 3038 00 a', designation: 'séparateur eau', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- CHASSIS ET STRUCTURE PRINCIPALE ---
  { id: 'st2g_60', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Cadre Avant', component: 'Plaques principales', subComponent: '', reference: '3128 3001 00 a', designation: 'Plaques principales', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_61', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Cadre Avant', component: 'Soudures', subComponent: '', reference: '3128 3001 00 b', designation: 'Soudures', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_62', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Cadre Avant', component: 'Boulons fixation', subComponent: '', reference: '3128 3001 00 c (kit)', designation: 'Boulons fixation (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_63', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Cadre Arrière', component: 'Plaques principales', subComponent: '', reference: '3128 3002 00 a', designation: 'Plaques principales', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_64', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Cadre Arrière', component: 'Points d\'ancrage', subComponent: '', reference: '3128 3002 00 b', designation: 'Points d\'ancrage', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_65', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Articulation Centrale', component: 'Roulements sphériques', subComponent: '', reference: '3128 0456 00 a', designation: 'Roulements sphériques', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_66', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Articulation Centrale', component: 'Pivots', subComponent: '', reference: '3128 0456 00 b', designation: 'Pivots', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_67', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Articulation Centrale', component: 'Joints', subComponent: '', reference: '3128 0456 00 c (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_68', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Protections Inférieures', component: 'Plaques Hardox', subComponent: '', reference: '5112 3100 00 a', designation: 'Plaques Hardox', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_69', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Protections Inférieures', component: 'Boulons fixation', subComponent: '', reference: '5112 3100 00 b (kit)', designation: 'Boulons fixation (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_70', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Pivots d Articulation', component: 'Axes', subComponent: '', reference: '3128 0457 00 a', designation: 'Axes', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_71', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Pivots d Articulation', component: 'Bagues bronze', subComponent: '', reference: '3128 0457 00 b (kit)', designation: 'Bagues bronze (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_72', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Boulons de Fixation chassis', component: 'Boulons M24', subComponent: '', reference: 'M24x3 Grade 10.9 a', designation: 'Boulons M24', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_73', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Boulons de Fixation chassis', component: 'écrous', subComponent: '', reference: 'M24x3 Grade 10.9 b', designation: 'écrous', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_74', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Plaques de Renforcement', component: 'Plaques latérales', subComponent: '', reference: '3128 0463 00 a', designation: 'Plaques latérales', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_75', functionalCategory: 'Chassis et Structure Principale', subCategory: 'Plaques de Renforcement', component: 'Boulons', subComponent: '', reference: '3128 0463 00 b (kit)', designation: 'Boulons (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- TRANSMISSION ET CONVERTISSEUR DE COUPLE ---
  { id: 'st2g_76', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Convertisseur de Couple', component: 'Turbine', subComponent: '', reference: '5513 3820 00 a', designation: 'Turbine', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_77', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Convertisseur de Couple', component: 'Stator', subComponent: '', reference: '5513 3820 00 b', designation: 'Stator', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_78', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Boite de Vitesses', component: 'Engrenages', subComponent: '', reference: '5580 0181 93 a', designation: 'Engrenages', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_79', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Boite de Vitesses', component: 'Disques', subComponent: '', reference: '5580 0181 93 b (kit)', designation: 'Disques (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_80', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Arbres de Transmission Avant', component: 'Joints universels', subComponent: '', reference: '3128 0457 00 a (avant)', designation: 'Joints universels', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_81', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Arbres de Transmission Avant', component: 'Arbre principal', subComponent: '', reference: '3128 0457 00 b (avant)', designation: 'Arbre principal', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_82', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Arbres de Transmission Avant', component: 'Joints universels', subComponent: '', reference: '3128 0457 01 a (arrière)', designation: 'Joints universels', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_83', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Arbres de Transmission Avant', component: 'Arbre principal', subComponent: '', reference: '3128 0457 01 b (arrière)', designation: 'Arbre principal', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_84', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Kit Réparation Convertisseur', component: 'Joints toriques', subComponent: '', reference: '5513 3821 00 a (kit)', designation: 'Joints toriques (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_85', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Kit Réparation Convertisseur', component: 'Roulements', subComponent: '', reference: '5513 3821 00 b (kit)', designation: 'Roulements (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_86', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Engrenages Planetaires', component: 'Engrenages', subComponent: '', reference: '5513 3822 00 a (kit)', designation: 'Engrenages (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_87', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Engrenages Planetaires', component: 'Supports', subComponent: '', reference: '5513 3822 00 b (kit)', designation: 'Supports (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_88', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Pompe Hydraulique Transmission', component: 'Rotor', subComponent: '', reference: '3128 3217 00 a', designation: 'Rotor', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_89', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Pompe Hydraulique Transmission', component: 'Joints', subComponent: '', reference: '3128 3217 00 b (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_90', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Filtres Transmission', component: 'Filtre principal', subComponent: '', reference: '5580 0181 94 a', designation: 'Filtre principal', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_91', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Filtres Transmission', component: 'Joint', subComponent: '', reference: '5580 0181 94 b', designation: 'Joint', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_92', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Différentiel et cardan', component: 'Différentiel', subComponent: 'différentiel complet avant', reference: '560 000 000', designation: 'différentiel complet avant', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_93', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Différentiel et cardan', component: 'Différentiel', subComponent: 'différentiel complet arriere', reference: '560 000 100', designation: 'différentiel complet arriere', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_94', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Différentiel et cardan', component: 'Différentiel', subComponent: 'Couronne et pignon', reference: '560 123 789', designation: 'Couronne et pignon', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_95', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Différentiel et cardan', component: 'Différentiel', subComponent: 'Couronne', reference: '560 124 100', designation: 'Couronne', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_96', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Différentiel et cardan', component: 'Différentiel', subComponent: 'pignon', reference: '560 124 200', designation: 'pignon', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_97', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Différentiel et cardan', component: 'cardan', subComponent: 'Cardan complet', reference: '560 200 000', designation: 'Cardan complet', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_98', functionalCategory: 'Transmission et Convertisseur de Couple', subCategory: 'Différentiel et cardan', component: 'cardan', subComponent: 'joint cardan', reference: '560 201 000', designation: 'joint cardan', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- ESSIEUX ET ROUES ---
  { id: 'st2g_99', functionalCategory: 'Essieux et Roues', subCategory: 'Essieu Avant', component: 'Différentiel', subComponent: '', reference: '5580 0083 35 a', designation: 'Différentiel', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_100', functionalCategory: 'Essieux et Roues', subCategory: 'Essieu Avant', component: 'Roulements', subComponent: '', reference: '5580 0083 35 b (kit)', designation: 'Roulements (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_101', functionalCategory: 'Essieux et Roues', subCategory: 'Essieu Avant', component: 'Joints', subComponent: '', reference: '5580 0083 35 c (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_102', functionalCategory: 'Essieux et Roues', subCategory: 'Essieu Arrière', component: 'Freins intégrés', subComponent: '', reference: '5580 0083 36 a', designation: 'Freins intégrés', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_103', functionalCategory: 'Essieux et Roues', subCategory: 'Essieu Arrière', component: 'Roulements', subComponent: '', reference: '5580 0083 36 b (kit)', designation: 'Roulements (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_104', functionalCategory: 'Essieux et Roues', subCategory: 'Demi Arbres', component: 'Arbre forgé', subComponent: '', reference: '5112 3101 00 a', designation: 'Arbre forgé', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_105', functionalCategory: 'Essieux et Roues', subCategory: 'Demi Arbres', component: 'Joints', subComponent: '', reference: '5112 3101 00 b (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_106', functionalCategory: 'Essieux et Roues', subCategory: 'Roulements Essieux', component: 'Roulements coniques', subComponent: '', reference: '5112 3102 00 a (kit)', designation: 'Roulements coniques (kit)', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_107', functionalCategory: 'Essieux et Roues', subCategory: 'Roulements Essieux', component: 'Graisseurs', subComponent: '', reference: '5112 3102 00 b', designation: 'Graisseurs', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_108', functionalCategory: 'Essieux et Roues', subCategory: 'Roulements Essieux', component: 'Roulement intérieur', subComponent: '', reference: '5516 0031 00 a', designation: 'Roulement intérieur', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_109', functionalCategory: 'Essieux et Roues', subCategory: 'Roulements Essieux', component: 'Roulement extérieur', subComponent: '', reference: '5516 0032 00 a', designation: 'Roulement extérieur', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_110', functionalCategory: 'Essieux et Roues', subCategory: 'Jantes', component: 'Jante acier', subComponent: '', reference: '5112 3105 00 a', designation: 'Jante acier', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_111', functionalCategory: 'Essieux et Roues', subCategory: 'Jantes', component: 'Boulons jante', subComponent: '', reference: '5112 3105 00 b (kit)', designation: 'Boulons jante (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_112', functionalCategory: 'Essieux et Roues', subCategory: 'Pneus Miniers', component: 'Bande de roulement', subComponent: '', reference: 'Standard 12.00-20 a', designation: 'Bande de roulement', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_113', functionalCategory: 'Essieux et Roues', subCategory: 'Pneus Miniers', component: 'Flancs', subComponent: '', reference: 'Standard 12.00-20 b', designation: 'Flancs', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- SYSTEME HYDRAULIQUE ---
  { id: 'st2g_114', functionalCategory: 'Systeme Hydraulique', subCategory: 'Pompe Principale', component: 'Piston axial', subComponent: '', reference: '3128 3217 63 a', designation: 'Piston axial', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_115', functionalCategory: 'Systeme Hydraulique', subCategory: 'Pompe Principale', component: 'Joints', subComponent: '', reference: '3128 3217 63 b (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_116', functionalCategory: 'Systeme Hydraulique', subCategory: 'Vérins de Godet', component: 'Tige chromée', subComponent: '', reference: '3128 3002 00 a', designation: 'Tige chromée', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_117', functionalCategory: 'Systeme Hydraulique', subCategory: 'Vérins de Godet', component: 'Joints et segments', subComponent: '', reference: '3128 3002 00 b (kit)', designation: 'Joints et segments (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_118', functionalCategory: 'Systeme Hydraulique', subCategory: 'Vérins de Bras', component: 'Tige chromée', subComponent: '', reference: '3128 3003 00 a', designation: 'Tige chromée', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_119', functionalCategory: 'Systeme Hydraulique', subCategory: 'Vérins de Bras', component: 'Joints et segments', subComponent: '', reference: '3128 3003 00 b (kit)', designation: 'Joints et segments (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_120', functionalCategory: 'Systeme Hydraulique', subCategory: 'Vérin de Direction', component: 'Tige chromée', subComponent: '', reference: '3128 3004 00 a', designation: 'Tige chromée', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_121', functionalCategory: 'Systeme Hydraulique', subCategory: 'Vérin de Direction', component: 'Joints', subComponent: '', reference: '3128 3004 00 b (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  { id: 'st2g_122', functionalCategory: 'Systeme Hydraulique', subCategory: 'Bloc de Valves Principal', component: 'Valves', subComponent: '', reference: '5580 0181 95 a', designation: 'Valves', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_123', functionalCategory: 'Systeme Hydraulique', subCategory: 'Bloc de Valves Principal', component: 'Joints', subComponent: '', reference: '5580 0181 95 b (kit)', designation: 'Joints (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- SYSTEME DE FREINAGE ET SECURITE ---
  { id: 'st2g_124', functionalCategory: 'Système de Freinage et Sécurité', subCategory: 'Disques de Freins kit', component: 'Disques', subComponent: '', reference: '5112 3102 00 a', designation: 'Disques', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_125', functionalCategory: 'Système de Freinage et Sécurité', subCategory: 'Plaquettes de Freins', component: 'Plaquettes composite', subComponent: '', reference: '5112 3103 00 a (kit)', designation: 'Plaquettes composite (kit)', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- GODET ET BRAS DE CHARGEMENT ---
  { id: 'st2g_126', functionalCategory: 'Godet et Bras de Chargement', subCategory: 'Godet Standard', component: 'Fond', subComponent: '', reference: '3128 3004 00 a', designation: 'Fond', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_127', functionalCategory: 'Godet et Bras de Chargement', subCategory: 'Dents de Godet Sharké', component: 'Pointe carbure', subComponent: '', reference: '5112 3104 00 a', designation: 'Pointe carbure', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- CABINE ET CONTROLES ---
  { id: 'st2g_128', functionalCategory: 'Cabine et Controles', subCategory: 'Structure Cabine Ouverte ROPS FOPS', component: 'Toit', subComponent: '', reference: '3128 0460 00 a', designation: 'Toit', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_129', functionalCategory: 'Cabine et Controles', subCategory: 'Siège Opérateur', component: 'Suspension', subComponent: '', reference: 'équivalent ancien a', designation: 'Suspension', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- SYSTEME ELECTRIQUE ET ECLAIRAGE ---
  { id: 'st2g_130', functionalCategory: 'Systeme Electrique et Eclairage', subCategory: 'Batteries', component: 'Cellules', subComponent: '', reference: '2 x 12V / 180 Ah a', designation: 'Cellules', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_131', functionalCategory: 'Systeme Electrique et Eclairage', subCategory: 'Alternateur', component: 'Rotor', subComponent: '', reference: '5516 0034 00 a', designation: 'Rotor', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- KITS DE MAINTENANCE ET CONSOMMABLES ---
  { id: 'st2g_132', functionalCategory: 'Kits de Maintenance et Consommables', subCategory: 'Kit Filtres 500 h', component: 'Filtre air', subComponent: '', reference: '5516 0027 00 a', designation: 'Filtre air', suggestedType: 'ENGINS', source: 'MASTER' },
  { id: 'st2g_133', functionalCategory: 'Kits de Maintenance et Consommables', subCategory: 'Huile Moteur', component: 'Bidon 20L', subComponent: '', reference: 'Huile 15W40 a', designation: 'Bidon 20L', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- ACCESSOIRES ET DIVERS ---
  { id: 'st2g_134', functionalCategory: 'Accessoires et Divers', subCategory: 'Bouchon Réservoir Gasoil', component: 'Bouchon', subComponent: '', reference: 'Bouchon gasoil ancien a', designation: 'Bouchon', suggestedType: 'ENGINS', source: 'MASTER' },

  // --- PERFORATEURS ---
  { id: 'perfo_01', functionalCategory: 'Corps Principal', subCategory: 'Boîtier', component: 'Corps central cylindre', subComponent: '', reference: 'MB-T23-001 / 86633697', designation: 'Corps forgé en acier haute résistance', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_02', functionalCategory: 'Corps Principal', subCategory: 'Boîtier', component: "Orifice d'échappement", subComponent: '', reference: 'MB-T23-001a', designation: 'Orifice pour évacuation air comprimé dans cylindre', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_03', functionalCategory: 'Corps Principal', subCategory: 'Boîtier', component: 'Eillet on chape', subComponent: '', reference: 'MB-T23-001b', designation: 'Eillet sur chape pour fixation poussoir', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_04', functionalCategory: 'Corps Principal', subCategory: 'Couvercle avant', component: '', subComponent: '', reference: 'MB-T23-002 / 86611647', designation: 'Logement shank et chuck', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_05', functionalCategory: 'Corps Principal', subCategory: 'Couvercle arrière', component: '', subComponent: '', reference: 'MB-T23-003 / 86374055', designation: 'Contient valve throttle et connexion hose air/eau', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_06', functionalCategory: 'Corps Principal', subCategory: 'Bouchon presse étoupe', component: '', subComponent: '', reference: 'MB-T23-005 / 86223443', designation: 'Bouchon pour étanchéité presse-étoupe', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_07', functionalCategory: 'Corps Principal', subCategory: 'Bouchon presse étoupe', component: 'Joint torique bouchon', subComponent: '', reference: 'MB-T23-005a / 86262698', designation: 'Petit joint torique pour bouchon presse-étoupe', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_08', functionalCategory: 'Corps Principal', subCategory: 'Bouchon', component: '', subComponent: '', reference: 'MB-T23-006', designation: 'Bouchon pour injection', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_09', functionalCategory: 'Corps Principal', subCategory: 'Fixations', component: 'Vis et écrous', subComponent: 'Vis de fixation M8', reference: 'MB-T23-004a / 86313228', designation: 'Vis M8 pour assemblage corps', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_10', functionalCategory: 'Corps Principal', subCategory: 'Fixations', component: 'Vis et écrous', subComponent: 'Vis de fixation M10', reference: 'MB-T23-004b / 86265048', designation: 'Vis M10 pour couvercles', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_11', functionalCategory: 'Corps Principal', subCategory: 'Fixations', component: 'Vis et écrous', subComponent: 'écrous auto-bloquants', reference: 'MB-T23-004c', designation: 'écrous pour vis corps', suggestedType: 'PERFORATEURS', source: 'MASTER' },

  { id: 'perfo_12', functionalCategory: 'Système de Percussion', subCategory: 'Piston', component: 'Piston de frappe', subComponent: '', reference: 'MB-T23-101 / 86611639', designation: 'Piston principal de frappe en alliage dur pour 2500 bpm', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_13', functionalCategory: 'Système de Percussion', subCategory: 'Piston', component: 'Piston de frappe', subComponent: 'Cannelures obliques/droites', reference: 'MB-T23-101a', designation: 'Cannelures sur piston pour rotation et entraînement', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_14', functionalCategory: 'Système de Percussion', subCategory: 'Bagues et joints', component: 'Joint torique supérieur', subComponent: '', reference: 'MB-T23-102a / 86616662', designation: 'Joint torique nitrile pour étanchéité supérieure piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_15', functionalCategory: 'Système de Percussion', subCategory: 'Bagues et joints', component: 'Joint torique inférieur', subComponent: '', reference: 'MB-T23-102b', designation: 'Joint torique pour base piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_16', functionalCategory: 'Système de Percussion', subCategory: 'Bagues et joints', component: 'Segments de piston', subComponent: '', reference: 'MB-T23-102c', designation: 'Segments pour compression air', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_17', functionalCategory: 'Système de Percussion', subCategory: "Bague d'étanchéité", component: '', subComponent: '', reference: 'MB-T23-102d / 86640299', designation: "Bague d'étanchéité pour queue de piston", suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_18', functionalCategory: 'Système de Percussion', subCategory: 'Valve', component: 'Distribution', subComponent: 'Boîte de distribution', reference: 'MB-T23-103c', designation: 'Boîte de distribution permet passage air vers piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_19', functionalCategory: 'Système de Percussion', subCategory: 'Valve', component: 'Distribution', subComponent: 'Distributeur principal', reference: 'MB-T23-103a / 86633697', designation: 'Valve de distribution contrôlant flux air pour frappe', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_20', functionalCategory: 'Système de Percussion', subCategory: 'Valve', component: 'Distribution', subComponent: 'Clapet anti-retour', reference: 'MB-T23-103b', designation: 'Clapet pour régulation flux', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_21', functionalCategory: 'Système de Percussion', subCategory: 'Valve', component: 'Distribution', subComponent: 'Valve', reference: 'MB-T23-103d / 86322518', designation: 'Valve envoie air comprimé vers face supérieure/inférieure piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_22', functionalCategory: 'Système de Percussion', subCategory: 'Valve', component: 'Distribution', subComponent: 'Siège de valve et fourreau', reference: 'MB-T23-103e', designation: 'Siège de valve et fourreau en matière plastique complètent chambre distribution', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_23', functionalCategory: 'Système de Percussion', subCategory: 'Ressorts et clapets', component: 'Ressort de retour valve', subComponent: '', reference: 'MB-T23-104a / 86366283', designation: 'Ressort hélicoïdal pour valve distribution', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_24', functionalCategory: 'Système de Percussion', subCategory: 'Ressorts et clapets', component: 'Clapet secondaire', subComponent: '', reference: 'MB-T23-104b', designation: 'Clapet petit pour ajustement fin', suggestedType: 'PERFORATEURS', source: 'MASTER' },

  { id: 'perfo_25', functionalCategory: 'Système de Rotation', subCategory: 'Mécanisme', component: 'Barre rifle', subComponent: '', reference: 'MB-T23-201 / 86313087', designation: 'Barre rifle pour rotation CCW à 250 rpm', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_26', functionalCategory: 'Système de Rotation', subCategory: 'Mécanisme', component: 'Ecrou rochet', subComponent: '', reference: 'MB-T23-205', designation: 'Ecrou pour mécanisme rochet', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_27', functionalCategory: 'Système de Rotation', subCategory: 'Mécanisme', component: 'Ecrou rochet', subComponent: 'Vis de blocage', reference: 'MB-T23-205a', designation: 'Petite vis pour bloquer ecrou rochet', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_28', functionalCategory: 'Système de Rotation', subCategory: 'Ratchet et pawl', component: 'Ensemble cliquet principal', subComponent: '', reference: 'MB-T23-202a', designation: 'Mécanisme ratchet pour transmission rotation', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_29', functionalCategory: 'Système de Rotation', subCategory: 'Ratchet et pawl', component: 'Cliquets', subComponent: '', reference: 'MB-T23-202c', designation: 'Cliquets (4x) avec poussoirs et ressorts', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_30', functionalCategory: 'Système de Rotation', subCategory: 'Ratchet et pawl', component: 'Ressorts et poussoirs de cliquets', subComponent: '', reference: 'MB-T23-202d', designation: 'Ressorts et poussoirs pour cliquets', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_31', functionalCategory: 'Système de Rotation', subCategory: 'Chuck (porte-outil)', component: '', subComponent: '', reference: 'MB-T23-203 / 86511441', designation: 'Chuck pour shank 22x108', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_32', functionalCategory: 'Système de Rotation', subCategory: 'Ensemble busette', component: '', subComponent: '', reference: 'MB-T23-206', designation: 'Ensemble busette (bushing) pour guidage outil ; comprend manchon cannelé en bronze entraîné par queue piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_33', functionalCategory: 'Système de Rotation', subCategory: 'Ensemble busette', component: 'Bague busette', subComponent: '', reference: 'MB-T23-206a', designation: 'Bague interne pour ensemble busette', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_34', functionalCategory: 'Système de Rotation', subCategory: 'Ensemble busette', component: 'Manchon cannelé', subComponent: '', reference: 'MB-T23-206b', designation: 'Manchon cannelé (cannelures droites en bronze) entraîné par queue piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_35', functionalCategory: 'Système de Rotation', subCategory: 'Ensemble busette', component: 'Joint', subComponent: '', reference: 'MB-T23-206c / 86313186', designation: 'Joint pour ensemble busette', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_36', functionalCategory: 'Système de Rotation', subCategory: 'Ensemble busette', component: 'Busette', subComponent: '', reference: 'MB-T23-206d', designation: 'Busette pour guidage', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_37', functionalCategory: 'Système de Rotation', subCategory: 'Ensemble busette', component: 'Douille', subComponent: '', reference: 'MB-T23-206e', designation: 'Douille pour maintien fleuret dans marteau', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_38', functionalCategory: 'Système de Rotation', subCategory: 'Décalage', component: '', subComponent: '', reference: 'MB-T23-207', designation: 'Décalage maintient le fleuret dans la douille du marteau', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_39', functionalCategory: 'Système de Rotation', subCategory: 'Axe de décalage', component: '', subComponent: '', reference: 'MB-T23-208', designation: 'Axe de décalage', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_40', functionalCategory: 'Système de Rotation', subCategory: 'Ressorts et verrous de décalage', component: '', subComponent: '', reference: 'MB-T23-209', designation: 'Ressorts et verrous pour décalage', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_41', functionalCategory: 'Système de Rotation', subCategory: 'Tampon', component: '', subComponent: '', reference: 'MB-T23-210', designation: 'Tampon pour axe de décalage', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_42', functionalCategory: 'Système de Rotation', subCategory: 'Fixations', component: 'Roulements', subComponent: 'Roulement à billes avant', reference: 'MB-T23-204a / 86484755', designation: 'Roulement scellé pour axe rotation avant', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_43', functionalCategory: 'Système de Rotation', subCategory: 'Fixations', component: 'Roulements', subComponent: 'Roulement à billes arrière', reference: 'MB-T23-204b', designation: 'Roulement pour axe arrière', suggestedType: 'PERFORATEURS', source: 'MASTER' },

  { id: 'perfo_44', functionalCategory: 'Système de Rinçage', subCategory: 'Rinçage', component: 'Tube d injection air ou eau', subComponent: '', reference: 'MB-T23-304', designation: 'Tube pour injection air/eau', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_45', functionalCategory: 'Système de Rinçage', subCategory: 'Rinçage', component: 'Tube d injection air ou eau', subComponent: 'Connecteur tube', reference: 'MB-T23-304a', designation: 'Connecteur rapide pour tube injection', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_46', functionalCategory: 'Système de Rinçage', subCategory: 'Rinçage', component: 'Tube d injection air ou eau', subComponent: 'Garniture du tube', reference: 'MB-T23-304b', designation: "Garniture du tube d'injection", suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_47', functionalCategory: 'Système de Rinçage', subCategory: 'Système rinçage', component: 'Valve rinçage', subComponent: '', reference: 'MB-T23-301a', designation: 'Valve intégrée pour contrôle air/eau', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_48', functionalCategory: 'Système de Rinçage', subCategory: 'Système rinçage', component: 'Nozzle (buse)', subComponent: '', reference: 'MB-T23-301b / 86645959', designation: 'Buse pour évacuation débris', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_49', functionalCategory: 'Système de Rinçage', subCategory: 'Système rinçage', component: "Genouillère d'injection d'eau", subComponent: '', reference: 'MB-T23-301c', designation: "Genouillère d'injection d'eau en lieu et place du bouchon", suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_50', functionalCategory: 'Système de Rinçage', subCategory: 'Système rinçage', component: 'Filtre de genouillère', subComponent: '', reference: 'MB-T23-301d', designation: 'Filtre pour genouillère injection', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_51', functionalCategory: 'Système de Rinçage', subCategory: 'Système rinçage', component: 'Axe de genouillère', subComponent: '', reference: 'MB-T23-301e', designation: 'Axe pour genouillère', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_52', functionalCategory: 'Système de Rinçage', subCategory: 'Système rinçage', component: 'Joints à lèvres/joint torique axe genouillère', subComponent: '', reference: 'MB-T23-301f', designation: 'Joints à lèvres ou torique pour axe genouillère', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_53', functionalCategory: 'Système de Rinçage', subCategory: 'Conduites internes', component: 'Hose interne air', subComponent: '', reference: 'MB-T23-302a', designation: 'Tube pour flux air', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_54', functionalCategory: 'Système de Rinçage', subCategory: 'Conduites internes', component: 'Hose interne eau', subComponent: '', reference: 'MB-T23-302b', designation: 'Tube pour rinçage eau', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_55', functionalCategory: 'Système de Rinçage', subCategory: 'Fixations', component: 'Joints rinçage', subComponent: 'Joint torique nozzle', reference: 'MB-T23-303a / 86307162', designation: 'Petit joint pour buse', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_56', functionalCategory: 'Système de Rinçage', subCategory: 'Fixations', component: 'Joints rinçage', subComponent: 'Joint gasket conduit', reference: 'MB-T23-303b', designation: 'Joint plat pour connexions', suggestedType: 'PERFORATEURS', source: 'MASTER' },

  { id: 'perfo_57', functionalCategory: 'Controles et Valves', subCategory: 'Commande', component: 'Valve throttle (boisseau)', subComponent: '', reference: 'MB-T23-401', designation: 'Valve principale pour air', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_58', functionalCategory: 'Controles et Valves', subCategory: 'Commande', component: 'Poignée T (option handheld)', subComponent: '', reference: 'MB-T23-402', designation: 'Poignée T anti-vib pour version manuelle (non-UE)', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_59', functionalCategory: 'Controles et Valves', subCategory: 'Commande', component: 'Commande air jackleg', subComponent: '', reference: 'MB-T23-403', designation: 'Valve for poussoir', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_60', functionalCategory: 'Controles et Valves', subCategory: 'Fixation', component: 'Levers et pins', subComponent: 'Lever de contrôle', reference: 'MB-T23-404a / 86302841', designation: 'Levier pour valve', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_61', functionalCategory: 'Controles et Valves', subCategory: 'Fixation', component: 'Levers et pins', subComponent: 'Pin de fixation', reference: 'MB-T23-404b', designation: 'Pin acier pour levers', suggestedType: 'PERFORATEURS', source: 'MASTER' },

  { id: 'perfo_62', functionalCategory: 'Pièces d Usure', subCategory: 'Joints Globaux', component: 'Kit joints complet', subComponent: 'Joint torique kit', reference: 'MB-T23-501a / 86483146', designation: 'Ensemble >20 joints toriques divers', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_63', functionalCategory: 'Pièces d Usure', subCategory: 'Joints Globaux', component: 'Kit joints complet', subComponent: 'Gaskets plats', reference: 'MB-T23-501b', designation: 'Joints plats pour couvercles', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_64', functionalCategory: 'Pièces d Usure', subCategory: 'Joints Globaux', component: 'Kit joints complet', subComponent: 'Seals piston secondaires', reference: 'MB-T23-501c / 86640299', designation: 'Seals additionnels pour piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_65', functionalCategory: 'Pièces d Usure', subCategory: 'Lubrification', component: 'Lubrificateur en ligne', subComponent: '', reference: 'MB-T23-502 / GM.4', designation: 'Lubrificateur GM.4', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_66', functionalCategory: 'Pièces d Usure', subCategory: 'Berceau', component: 'Cradle pour jackleg', subComponent: '', reference: 'MB-T23-503 / 86246899', designation: 'Berceau montage sur poussoir', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_67', functionalCategory: 'Pièces d Usure', subCategory: 'Filtre', component: 'Filtre air entrée', subComponent: 'Filtre mesh principal', reference: 'MB-T23-504a', designation: 'Filtre mesh anti-poussière', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_68', functionalCategory: 'Pièces d Usure', subCategory: 'Filtre', component: 'Filtre air entrée', subComponent: 'Filtre secondaire', reference: 'MB-T23-504b', designation: 'Filtre fin pour air', suggestedType: 'PERFORATEURS', source: 'MASTER' },

  { id: 'perfo_69', functionalCategory: 'Accessoires de Forage', subCategory: 'Poussoir', component: 'Jackleg standard', subComponent: '', reference: 'MB-T23-601 / C180', designation: 'Poussoir télescopique AJA 205', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_70', functionalCategory: 'Accessoires de Forage', subCategory: 'Poussoir', component: 'Distributeur complet', subComponent: '', reference: 'MB-T23-601a / 86241577', designation: 'Distributeur air pour AJA 205', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_71', functionalCategory: 'Accessoires de Forage', subCategory: 'Poussoir', component: 'Berceau', subComponent: '', reference: 'MB-T23-601b / 86246899', designation: 'Berceau pour montage', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_72', functionalCategory: 'Accessoires de Forage', subCategory: 'Poussoir', component: 'Graisseur', subComponent: '', reference: 'MB-T23-601c / 86239886', designation: 'Graisseur pour AJA 205', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_73', functionalCategory: 'Accessoires de Forage', subCategory: 'Barres Coniques', component: 'Barre 1.8m', subComponent: '', reference: 'MB-T23-701', designation: 'Barre conique 1.8m', suggestedType: 'PERFORATEURS', source: 'MASTER', price: 1200 },
  { id: 'perfo_74', functionalCategory: 'Accessoires de Forage', subCategory: 'Barres Coniques', component: 'Barre 2.4m', subComponent: '', reference: 'MB-T23-702', designation: 'Barre conique 2.4m', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_75', functionalCategory: 'Accessoires de Forage', subCategory: 'Barres Coniques', component: 'Adaptateurs', subComponent: '', reference: 'MB-T23-703 / 90516509', designation: 'Adaptateur shank pour barres', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_76', functionalCategory: 'Accessoires de Forage', subCategory: 'Taillants', component: 'Taillant 38mm', subComponent: '', reference: 'MB-T23-801a', designation: 'Taillant button 38mm', suggestedType: 'PERFORATEURS', source: 'MASTER' },

  { id: 'perfo_77', functionalCategory: 'Maintenance Generale', subCategory: 'Kits', component: 'Kit réparation complet', subComponent: '', reference: 'MB-T23-901 / 86483146', designation: 'Kit seals', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_78', functionalCategory: 'Maintenance Generale', subCategory: 'Outils', component: 'Outils de montage', subComponent: 'Clé torque', reference: 'MB-T23-902a', designation: 'Clé torque pour vis', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_79', functionalCategory: 'Maintenance Generale', subCategory: 'Outils', component: 'Outils de montage', subComponent: 'Extracteur piston', reference: 'MB-T23-902b', designation: 'Extracteur pour piston', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_80', functionalCategory: 'Maintenance Generale', subCategory: 'Lubrifiants', component: 'Huile et graisse', subComponent: 'Huile Montabert', reference: 'MB-T23-904a', designation: 'Huile pour lubrificateur', suggestedType: 'PERFORATEURS', source: 'MASTER' },
  { id: 'perfo_81', functionalCategory: 'Maintenance Generale', subCategory: 'Lubrifiants', component: 'Huile et graisse', subComponent: 'Graisse EP2', reference: 'MB-T23-904b', designation: 'Graisse pour ratchet', suggestedType: 'PERFORATEURS', source: 'MASTER' }

];
