import { CatalogItem } from './types';

export interface OutilPriceConfig {
  id: string;
  reference: string;
  designation: string;
  basePrice: number;
  sellingPrice: number;
  currency: string;
  lastUpdated: string;
  updatedBy: string;
}

export const OUTILS_PRICES: OutilPriceConfig[] = [
  {
    id: 'out_cle_01',
    reference: 'OUT-CLE-001',
    designation: 'Jeu de clés mixtes 6-22mm (12 pcs)',
    basePrice: 150,
    sellingPrice: 150,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_dyn_01',
    reference: 'OUT-DYN-001',
    designation: 'Clé dynamométrique 1/2" 40-200 Nm',
    basePrice: 350,
    sellingPrice: 350,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_tou_01',
    reference: 'OUT-TOU-001',
    designation: 'Jeu de tournevis (6 pcs)',
    basePrice: 65,
    sellingPrice: 65,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_pin_01',
    reference: 'OUT-PIN-001',
    designation: 'Pince multiprise 250mm',
    basePrice: 35,
    sellingPrice: 35,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_mar_01',
    reference: 'OUT-MAR-001',
    designation: 'Marteau boule 1kg manche fibre',
    basePrice: 45,
    sellingPrice: 45,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_sou_01',
    reference: 'OUT-SOU-001',
    designation: 'Poste soudeur MMA 200A inverter',
    basePrice: 1100,
    sellingPrice: 1100,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_bag_01',
    reference: 'OUT-BAG-001',
    designation: 'Baguettes électrodes 2,5mm (5kg)',
    basePrice: 100,
    sellingPrice: 100,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_gra_01',
    reference: 'OUT-GRA-001',
    designation: 'Pompe à graisse manuelle 500cc',
    basePrice: 200,
    sellingPrice: 200,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_cha_01',
    reference: 'OUT-CHA-001',
    designation: 'Clé à choc pneumatique 1/2"',
    basePrice: 550,
    sellingPrice: 550,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_ext_01',
    reference: 'OUT-EXT-001',
    designation: 'Extracteur de roulement 3 griffes',
    basePrice: 120,
    sellingPrice: 120,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_cou_01',
    reference: 'OUT-COU-001',
    designation: 'Pied à coulisse 150mm inox',
    basePrice: 80,
    sellingPrice: 80,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'out_boi_01',
    reference: 'OUT-BOI-001',
    designation: 'Boîte à outils complète 50 pcs',
    basePrice: 450,
    sellingPrice: 450,
    currency: 'MAD',
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system',
  },
];

const getPrice = (id: string): number => {
  const config = OUTILS_PRICES.find(p => p.id === id);
  return config?.sellingPrice || 0;
};

const RAW_ITEMS: Array<Record<string, any>> = [
  {
    id: 'out_cle_01',
    reference: 'OUT-CLE-001',
    designation: 'Jeu de clés mixtes 6-22mm (12 pcs)',
    unit: 'JEU',
    price: getPrice('out_cle_01'),
    functionalCategory: 'Clés & Cliquets',
    component: 'Clés mixtes',
    subComponent: 'Acier Chrome Vanadium',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 15,
    minStock: 5,
    criticalStock: 2,
    leadTimeDays: 7,
    commonName: 'Jeu clés 6-22',
    searchTags: ['clés', 'mixtes', 'cliquet', 'outils', 'serrage'],
    notes: 'Support de rangement en plastique fourni',
  },
  {
    id: 'out_dyn_01',
    reference: 'OUT-DYN-001',
    designation: 'Clé dynamométrique 1/2" 40-200 Nm',
    unit: 'PIECE',
    price: getPrice('out_dyn_01'),
    functionalCategory: 'Clés & Cliquets',
    component: 'Clé dynamométrique',
    subComponent: 'Mécanisme de précision',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 6,
    minStock: 2,
    criticalStock: 1,
    leadTimeDays: 14,
    commonName: 'Dynamo 1/2',
    searchTags: ['clé', 'dynamométrique', 'couple', 'serrage', 'précision'],
    notes: 'Livré avec certificat d\'étalonnage constructeur',
  },
  {
    id: 'out_tou_01',
    reference: 'OUT-TOU-001',
    designation: 'Jeu de tournevis (6 pcs)',
    unit: 'JEU',
    price: getPrice('out_tou_01'),
    functionalCategory: 'Tournevis',
    component: 'Tournevis',
    subComponent: 'Manches bi-matière anti-glisse',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 25,
    minStock: 8,
    criticalStock: 3,
    leadTimeDays: 5,
    commonName: 'Tournevis plat/cruci',
    searchTags: ['tournevis', 'vis', 'outillage', 'plat', 'cruciforme'],
    notes: 'Lames magnétiques en acier S2 résistant',
  },
  {
    id: 'out_pin_01',
    reference: 'OUT-PIN-001',
    designation: 'Pince multiprise 250mm',
    unit: 'PIECE',
    price: getPrice('out_pin_01'),
    functionalCategory: 'Pinces',
    component: 'Pince multiprise',
    subComponent: 'Branches gainées PVC',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 30,
    minStock: 10,
    criticalStock: 4,
    leadTimeDays: 5,
    commonName: 'Multiprise 250',
    searchTags: ['pince', 'multiprise', 'serrage', 'mâchoires'],
    notes: 'Charnière entrepassée 7 positions de réglage',
  },
  {
    id: 'out_mar_01',
    reference: 'OUT-MAR-001',
    designation: 'Marteau boule 1kg manche fibre',
    unit: 'PIECE',
    price: getPrice('out_mar_01'),
    functionalCategory: 'Marteaux & Masses',
    component: 'Marteau',
    subComponent: 'Manche en fibre de verre incassable',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 18,
    minStock: 5,
    criticalStock: 2,
    leadTimeDays: 5,
    commonName: 'Marteau 1kg',
    searchTags: ['marteau', 'boule', 'frappe', 'masse'],
    notes: 'Tête en acier forgé traité thermiquement',
  },
  {
    id: 'out_sou_01',
    reference: 'OUT-SOU-001',
    designation: 'Poste soudeur MMA 200A inverter',
    unit: 'PIECE',
    price: getPrice('out_sou_01'),
    functionalCategory: 'Équipement Soudure',
    component: 'Poste à souder',
    subComponent: 'Technologie IGBT Inverter',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 4,
    minStock: 1,
    criticalStock: 1,
    leadTimeDays: 15,
    commonName: 'Poste à souder 200A',
    searchTags: ['soudeur', 'mma', 'poste', 'soudure', 'arc'],
    notes: 'Écran LCD de réglage, complet avec câbles et pince de masse',
  },
  {
    id: 'out_bag_01',
    reference: 'OUT-BAG-001',
    designation: 'Baguettes électrodes 2,5mm (5kg)',
    unit: 'BOITE',
    price: getPrice('out_bag_01'),
    functionalCategory: 'Consommables Soudure',
    component: 'Électrodes',
    subComponent: 'Enrobage rutilo-basique',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 35,
    minStock: 10,
    criticalStock: 5,
    leadTimeDays: 7,
    commonName: 'Baguettes 2.5',
    searchTags: ['baguettes', 'electrodes', 'soudure', 'acier'],
    notes: 'Soudage toutes positions des aciers courants',
  },
  {
    id: 'out_gra_01',
    reference: 'OUT-GRA-001',
    designation: 'Pompe à graisse manuelle 500cc',
    unit: 'PIECE',
    price: getPrice('out_gra_01'),
    functionalCategory: 'Lubrification',
    component: 'Pompe à graisse',
    subComponent: 'Corps en acier renforcé',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 20,
    minStock: 6,
    criticalStock: 3,
    leadTimeDays: 5,
    commonName: 'Pompe graisse',
    searchTags: ['graisse', 'lubrification', 'pompe', 'cartouche'],
    notes: 'Pression de travail 400 bar, livré avec flexible et agrafe',
  },
  {
    id: 'out_cha_01',
    reference: 'OUT-CHA-001',
    designation: 'Clé à choc pneumatique 1/2"',
    unit: 'PIECE',
    price: getPrice('out_cha_01'),
    functionalCategory: 'Outillage Pneumatique',
    component: 'Clé à choc',
    subComponent: 'Mécanisme à double marteau',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 5,
    minStock: 2,
    criticalStock: 1,
    leadTimeDays: 14,
    commonName: 'Pétard 1/2',
    searchTags: ['choc', 'pneumatique', 'clé', 'pétard', 'boulonneuse'],
    notes: 'Couple max 1200 Nm, raccord d\'air 1/4" BSP',
  },
  {
    id: 'out_ext_01',
    reference: 'OUT-EXT-001',
    designation: 'Extracteur de roulement 3 griffes',
    unit: 'PIECE',
    price: getPrice('out_ext_01'),
    functionalCategory: 'Extracteurs',
    component: 'Extracteur',
    subComponent: 'Bras en acier forgé robuste',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 10,
    minStock: 3,
    criticalStock: 1,
    leadTimeDays: 10,
    commonName: 'Arrache moyeu',
    searchTags: ['extracteur', 'roulement', 'griffes', 'arrache'],
    notes: 'Diamètre d\'écartement max 150mm, réversible intérieur/extérieur',
  },
  {
    id: 'out_cou_01',
    reference: 'OUT-COU-001',
    designation: 'Pied à coulisse 150mm inox',
    unit: 'PIECE',
    price: getPrice('out_cou_01'),
    functionalCategory: 'Instruments de Mesure',
    component: 'Pied à coulisse',
    subComponent: 'Acier inoxydable trempé',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 12,
    minStock: 4,
    criticalStock: 1,
    leadTimeDays: 7,
    commonName: 'Pied à coulisse',
    searchTags: ['pied', 'coulisse', 'mesure', 'inox', 'calibre'],
    notes: 'Lecture au 1/20ème de mm, jauge de profondeur plate',
  },
  {
    id: 'out_boi_01',
    reference: 'OUT-BOI-001',
    designation: 'Boîte à outils complète 50 pcs',
    unit: 'PIECE',
    price: getPrice('out_boi_01'),
    functionalCategory: 'Rangement & Boîtes',
    component: 'Boîte à outils',
    subComponent: 'Coffret rigide en ABS antichoc',
    compatibility: 'Tous engins & perforateurs',
    suggestedType: 'OUTILS_TRAVAUX',
    stockQty: 8,
    minStock: 3,
    criticalStock: 1,
    leadTimeDays: 10,
    commonName: 'Caisse outils',
    searchTags: ['boîte', 'coffret', 'outils', 'complet', 'caisse'],
    notes: 'Contient l\'essentiel pour la maintenance de premier niveau',
  },
];

export const OUTILS_CATALOG: CatalogItem[] = RAW_ITEMS.map(it => ({
  id: it.id,
  reference: it.reference,
  designation: it.designation,
  unit: it.unit,
  price: getPrice(it.id),
  functionalCategory: it.functionalCategory,
  component: it.component,
  subComponent: it.subComponent,
  compatibility: it.compatibility,
  suggestedType: it.suggestedType,
  stockQty: it.stockQty,
  minStock: it.minStock,
  criticalStock: it.criticalStock,
  leadTimeDays: it.leadTimeDays,
  commonName: it.commonName,
  searchTags: it.searchTags,
  notes: it.notes,
})) as CatalogItem[];

export function updateOutilPrice(
  id: string,
  newPrice: number,
  updatedBy: string = 'magasinier'
): boolean {
  const config = OUTILS_PRICES.find(p => p.id === id);
  if (!config) return false;
  config.basePrice = newPrice;
  config.sellingPrice = newPrice;
  config.lastUpdated = new Date().toISOString();
  config.updatedBy = updatedBy;
  
  // Also update corresponding catalog item price inside OUTILS_CATALOG
  const catalogItem = OUTILS_CATALOG.find(item => item.id === id);
  if (catalogItem) {
    catalogItem.price = newPrice;
  }
  return true;
}

export function getAllOutilsPrices(): OutilPriceConfig[] {
  return [...OUTILS_PRICES];
}
